FROM apache/nifi-registry:0.7.0

COPY --chown=nifi:nifi flow_storage /opt/nifi-registry/nifi-registry-current/flow_storage
COPY --chown=nifi:nifi database /opt/nifi-registry/nifi-registry-current/database
